theme: jekyll-theme-minimal
title: The Grimoire of Heart
description: [Download the latest version here.](https://github.com/grimoireofheart/grimoireofheart.github.io/blob/a003950bf6f146422af122092806b3ab89b1e1b8/Resources/Grimoire%20of%20the%20Heart%20v4.4.7%20EN.pdf).
